version: '3.9'
services:
  train:
    build:
      context: .
      dockerfile: train.Dockerfile
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    image: uyw-train
    container_name: uyw-train
    volumes:
      - .:/workspace
    stdin_open: true
    tty: true
    environment:
      - HUGGINGFACE_TOKEN
  infer:
    build:
      context: .
      dockerfile: infer.Dockerfile
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    image: uyw-infer
    container_name: uyw-infer
    volumes:
      - .:/workspace
    stdin_open: true
    tty: true
